# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79fc538527fe9e89b4efc6ac6394e55f820310ed1ec5d6ad386a365d9f6d896b65b403631d3db5deef9161b4d03f44d99893cbd1ed3607dc301d47fd1b8156fc

test:
  secret_key_base: 9e3204afc112e3e39caadae28619e79812e4367381484b4651ff17b37319cd40d44d8d6d51643ad19af8d92e1630208a5c9f0b49d5ce671caca47e3cd2522efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
